config/routes.rb
Rails.application.routes.draw do
  # get 'profile/index'
  get "/profile", to: "profile#index", as: "profile"

  devise_for :users

  resources :posts do
    collection do
      get '/json/:username' => 'posts#json', as: :json
    end
    collection do
      get :public
    end
    collection do
      get :private
    end
  end

  root 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:json]

  def index
    @posts = current_user.posts.order('created_at DESC')
    @username = current_user.username
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.slug = @post.title.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')

    if @post.save
      redirect_to current_user.posts.last
    else
      render 'new'
    end
  end

  def show
    redirect_to root_path
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def json
    @user = User.where(:username => params[:username])

    if !@user.ids.present?
      response = {
        "status": 404,
        "success": false
      }
    else
      # only display public posts
      @posts = Post.where(:user_id => @user.ids, :private => 0)
      response = @posts.order('created_at DESC')
    end

    render json: response
  end

  def public
    @posts = current_user.posts.where(:private => 0).order('created_at DESC')
    @username = current_user.username
    render 'index'
  end

  def private
    @posts = current_user.posts.where(:private => 1).order('created_at DESC')
    @username = current_user.username
    render 'index'
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :topic, :author, :private)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    @user = current_user
    @posts = current_user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/application/_header.html.erb
<header class='main-header'>
  <div class='wrapper'>
    <div class='logo-container'>
      <i class='material-icons sidebar-toggle'>subject</i>
      <h1 class='logo'><span>Type</span>wryter</h1>
    </div>
    <div class='header-menu'>
      <div><%= active_link_to 'Dashboard', root_path, method: :get, :wrap_tag => :div, :active => [['posts'], ['index', 'public', 'private']] %></div>
      <div><%= active_link_to 'New Post', new_post_path, method: :get, :wrap_tag => :div, :active => [['posts'], ['new', 'edit']] %></div>
      <div><%= active_link_to 'Profile', profile_path, method: :get, :wrap_tag => :div, :active => :exclusive %></div>
      <div><%= active_link_to 'Logout', destroy_user_session_path, method: :delete, :wrap_tag => :div, :active => :exclusive %></div>
    </div>
  </div>
</header>

app/views/application/_separator.html.erb
<i class="separator"> </i>

app/views/application/_sidebar.html.erb
<div class='sidebar'>
  <div class='sidebar-menu'>
    <li><%= active_link_to 'Dashboard', root_path, method: :get, :wrap_tag => :li, :active => :exclusive %></li>
    <li><%= active_link_to 'New Post', new_post_path, method: :get, :wrap_tag => :li, :active => :exclusive %></li>
    <li><%= active_link_to 'Logout', destroy_user_session_path, method: :delete, :wrap_tag => :li, :active => :exclusive %></li>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Typewryter</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= tinymce_assets %>
<div class='post-form-container'>
<%= form_for @post do |f| %>
  <%= f.text_field :title, :class => 'post-form-title', placeholder: 'Title', :title => 'title' %>
  <div class='tinymce-container'><%= raw(@post.body) %></div>
  <%= f.text_area :body, :class => 'tinymce-textarea' %>
  <div class='post-form-wrapper'>
  <%= f.text_field :topic, :class => 'post-form-topic', placeholder: 'Topic', :title => 'topic' %>
  <%= f.submit 'Publish', :class => 'submit-btn' %>
  <div class='post-form-privacy'><span><%= f.check_box :private %></span> Private</div>
  </div>
<% end %>
</div>
<script type="text/javascript">
  tinymce.init({
    selector: '.tinymce-container',
    inline: true,
    theme: 'inlite',
    skin: 'blue',
    toolbar: 'fontselect fontsizeselect | styleselect | removeformat | bullist numlist outdent indent | image link codesample | code preview',
    statusbar: false,
    menubar: false
  })
  $(window).keypress(function () {
    $('.tinymce-textarea').val($('.tinymce-container').html())
  })
</script>

app/views/posts/edit.html.erb
<%= render 'application/sidebar' %>
<div class='container'>
  <%= render 'application/header' %>
  <div class='form'>
    <%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'application/sidebar' %>
<div class='container'>
<%= render 'application/header' %>
<div class='wrapper'>
<div class="index-menu">
  <div>
    <%= active_link_to 'All', root_path, method: :get, :wrap_tag => :div, :active => :exclusive %>
  </div>
  <div>
    <%= active_link_to 'Public', public_posts_path, method: :get, :wrap_tag => :div, :active => :exclusive %>
  </div>
  <div>
    <%= active_link_to 'Private', private_posts_path, method: :get, :wrap_tag => :div, :active => :exclusive %>
  </div>
  <div>
    <%= active_link_to 'JSON', json_posts_path(username: @username), method: :get, :wrap_tag => :div, :active => :exclusive %>
  </div>
</div>
</div>
<div class='flex-container'>
  <% @posts.each do |post| %>
  <div class='post-container'>
    <div class='post-tools'>
      <button class='post-info-toggle'>
        <span>
          <i class='material-icons info-toggle'>list</i>
        </span>
      </button>
      <%= link_to edit_post_path(post[:id]) do %>
        <button class='post-edit-toggle'>
          <span>
            <i class='material-icons'>mode_edit</i>
          </span>
        </button>
      <% end %>
      <%= link_to post_path(post[:id]), method: :delete do %>
        <button class='post-delete-toggle'>
          <span>
            <i class='material-icons'>delete</i>
          </span>
        </button>
      <% end%>
    </div>
      <article class='post'>
        <h1 class='title'>
          <%= post[:title] %>
        </h1>
        <div class='content'>
          <div class='content-body'>
            <%= post[:body].html_safe %>
          </div>
          <div class='content-post'>
            <%=
              "<strong>Length</strong>
              <br>
              #{post[:body].split(' ').length} words<br>".html_safe
            %>
            <br>
            <%=
              "<strong>Topic</strong>
              <br>
              #{post[:topic]}<br>".html_safe
            %>
            <br>
            <%=
              "<strong>Created</strong>
              <br>
              #{post[:created_at].strftime("%B %d, %Y")}<br>".html_safe
            %>
            <br>
            <%=
              "<strong>Last Updated</strong>
              <br>
              #{time_ago_in_words(post[:updated_at])} ago<br>".html_safe
            %>
            <br>
            <%=
              "<strong>Privacy</strong>
              <br>
              #{post[:private] == "0" ? "public" : "private"}<br>".html_safe
            %>
          </div>
        </div>
      </article>
  </div>
  <% end %>
</div>
</div>

app/views/posts/json.html.erb
<%= @posts %>

app/views/posts/new.html.erb
<%= render 'application/sidebar' %>
<div class='container'>
  <%= render 'application/header' %>
  <div class='form'>
    <%= render 'form' %>
  </div>
</div>